extern __thread unsigned long __core_fault_mask;
extern __thread unsigned long __core_employ_mask;
extern __thread unsigned long __core_unemploy_mask;
extern __thread unsigned long __core_spawn_mask;
extern __thread unsigned long __id_spawn_mask;
extern __thread  int __spawn_tag;
extern __thread int __spawn_thread_num;
extern __thread int __sig_join_tag ;
extern __thread int __sig_end_tag[MAX_CORES];
//extern __thread thread_info_t * __v_thread_info;
extern thread_info_t __v_thread_info[4][MAX_CORES];
extern __thread int __max_threads;
extern __thread unsigned long __id_use_mask;
extern __thread unsigned long __core_use_mask;
